// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是暴露给前端的 Wails 应用对象。
 * 所有前端通过 v3 自动生成的 bindings 调用的方法都挂在 App 上。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "./internal/agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddServer 添加服务器，返回新 ID。
 */
export function AddServer($in: $models.AddServerInput): $CancellablePromise<string> {
    return $Call.ByID(755592719, $in);
}

/**
 * AddTunnel 添加映射，返回新 ID。
 * 按 protocol 调用 agent 在线校验/分配端口或域名，失败则返回 error 不落库。
 */
export function AddTunnel($in: $models.AddTunnelInput): $CancellablePromise<string> {
    return $Call.ByID(1252415046, $in);
}

/**
 * CheckServerCapabilities 查询服务端能力。
 */
export function CheckServerCapabilities(serverId: string): $CancellablePromise<agent$0.Capabilities | null> {
    return $Call.ByID(911576626, serverId);
}

/**
 * Close 释放 App 持有的资源（供测试清理调用）。
 * 生产环境由 ServiceShutdown 负责。
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(906152507);
}

/**
 * DeleteServer 删除服务器，并尝试通过 agent 释放其下映射占用的服务端资源。
 */
export function DeleteServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(963928181, id);
}

/**
 * DeleteTunnel 删除映射，并释放服务端资源。
 */
export function DeleteTunnel(id: string): $CancellablePromise<void> {
    return $Call.ByID(2127640780, id);
}

/**
 * EmitLog 向前端推送一条日志（通过 Wails v3 事件 log:append）。
 */
export function EmitLog(level: string, message: string, serverID: string): $CancellablePromise<void> {
    return $Call.ByID(4241904664, level, message, serverID);
}

/**
 * GenerateFrpcConfig 根据指定服务器的映射生成 frpc.toml 内容。
 */
export function GenerateFrpcConfig(serverId: string): $CancellablePromise<string> {
    return $Call.ByID(2145087677, serverId);
}

/**
 * InitForTest 注入测试依赖，不经过 Wails 运行时。
 */
export function InitForTest(dbPath: string): $CancellablePromise<void> {
    return $Call.ByID(919581334, dbPath);
}

/**
 * IsFrpcRunning 返回指定服务器的 frpc 是否在运行。
 */
export function IsFrpcRunning(serverId: string): $CancellablePromise<boolean> {
    return $Call.ByID(398476967, serverId);
}

/**
 * ListServers 返回所有服务器。
 */
export function ListServers(): $CancellablePromise<$models.ServerInfo[] | null> {
    return $Call.ByID(3825619783);
}

/**
 * ListTunnels 返回指定服务器的映射；serverId 为空则返回全部。
 */
export function ListTunnels(serverId: string): $CancellablePromise<$models.TunnelInfo[] | null> {
    return $Call.ByID(3790133688, serverId);
}

/**
 * RestartFrpc 重启指定服务器的 frpc 进程。
 */
export function RestartFrpc(serverId: string): $CancellablePromise<void> {
    return $Call.ByID(2319016453, serverId);
}

/**
 * SetApplication 注入 Wails v3 应用实例（由 main.go 在 application.New 后回填）。
 * 供 EmitLog 等通过 app.Event.Emit 推送事件到前端。
 */
export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4121261467, app);
}

/**
 * StartFrpc 启动指定服务器的 frpc 进程，并转发其输出为日志事件。
 */
export function StartFrpc(serverId: string): $CancellablePromise<void> {
    return $Call.ByID(3379011934, serverId);
}

/**
 * StopFrpc 停止指定服务器的 frpc 进程。
 */
export function StopFrpc(serverId: string): $CancellablePromise<void> {
    return $Call.ByID(591840712, serverId);
}

/**
 * UpdateServerByID 按 ID 更新服务器。
 */
export function UpdateServerByID(id: string, $in: $models.AddServerInput): $CancellablePromise<void> {
    return $Call.ByID(2176992823, id, $in);
}

/**
 * UpdateTunnelByID 按 ID 更新映射。
 */
export function UpdateTunnelByID(id: string, $in: $models.AddTunnelInput): $CancellablePromise<void> {
    return $Call.ByID(3590828754, id, $in);
}
