// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AddServerInput 是添加服务器的输入参数。
 */
export interface AddServerInput {
    "name": string;
    "host": string;
    "frps_port": number;
    "frp_token": string;
    "agent_url": string;
    "agent_token": string;
    "is_default": boolean;
    "remark": string;
}

/**
 * AddTunnelInput 是添加映射的输入参数。
 */
export interface AddTunnelInput {
    "server_id": string;
    "name": string;
    "protocol": string;
    "local_ip": string;
    "local_port": number;
    "remote_port"?: number;
    "custom_domain"?: string;
    "subdomain"?: string;
}

/**
 * ServerInfo 对应客户端 SQLite servers 表，前端通过 Wails 绑定接收。
 * 字段使用 snake_case 以匹配前端 TS 接口（Wails 会保留 Go 字段名的 json tag 形式）。
 */
export interface ServerInfo {
    "id": string;
    "name": string;
    "host": string;
    "frps_port": number;
    "frp_token": string;
    "agent_url": string;
    "agent_token": string;
    "is_default": boolean;
    "remark": string;
}

/**
 * Tray 封装系统托盘与主窗口的生命周期绑定。
 * 关闭窗口时根据 settings.CloseToTray 决定是隐藏到托盘还是真正退出。
 */
export interface Tray {
}

/**
 * TunnelInfo 对应客户端 SQLite tunnels 表。
 */
export interface TunnelInfo {
    "id": string;
    "server_id": string;
    "name": string;

    /**
     * tcp | udp | http | https
     */
    "protocol": string;
    "local_ip": string;
    "local_port": number;
    "remote_port"?: number;
    "custom_domain"?: string;
    "subdomain"?: string;
    "enabled": boolean;
    "status": string;
}
