// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AddServerInput 是添加服务器的输入参数。
 */
export class AddServerInput {
    "name": string;
    "host": string;
    "frps_port": number;
    "frp_token": string;
    "agent_url": string;
    "agent_token": string;
    "is_default": boolean;
    "remark": string;

    /** Creates a new AddServerInput instance. */
    constructor($$source: Partial<AddServerInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("frps_port" in $$source)) {
            this["frps_port"] = 0;
        }
        if (!("frp_token" in $$source)) {
            this["frp_token"] = "";
        }
        if (!("agent_url" in $$source)) {
            this["agent_url"] = "";
        }
        if (!("agent_token" in $$source)) {
            this["agent_token"] = "";
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddServerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AddServerInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddServerInput($$parsedSource as Partial<AddServerInput>);
    }
}

/**
 * AddTunnelInput 是添加映射的输入参数。
 */
export class AddTunnelInput {
    "server_id": string;
    "name": string;
    "protocol": string;
    "local_ip": string;
    "local_port": number;
    "remote_port"?: number;
    "custom_domain"?: string;
    "subdomain"?: string;

    /** Creates a new AddTunnelInput instance. */
    constructor($$source: Partial<AddTunnelInput> = {}) {
        if (!("server_id" in $$source)) {
            this["server_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("local_ip" in $$source)) {
            this["local_ip"] = "";
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddTunnelInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AddTunnelInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddTunnelInput($$parsedSource as Partial<AddTunnelInput>);
    }
}

/**
 * ServerInfo 对应客户端 SQLite servers 表，前端通过 Wails 绑定接收。
 * 字段使用 snake_case 以匹配前端 TS 接口（Wails 会保留 Go 字段名的 json tag 形式）。
 */
export class ServerInfo {
    "id": string;
    "name": string;
    "host": string;
    "frps_port": number;
    "frp_token": string;
    "agent_url": string;
    "agent_token": string;
    "is_default": boolean;
    "remark": string;

    /** Creates a new ServerInfo instance. */
    constructor($$source: Partial<ServerInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("frps_port" in $$source)) {
            this["frps_port"] = 0;
        }
        if (!("frp_token" in $$source)) {
            this["frp_token"] = "";
        }
        if (!("agent_url" in $$source)) {
            this["agent_url"] = "";
        }
        if (!("agent_token" in $$source)) {
            this["agent_token"] = "";
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfo($$parsedSource as Partial<ServerInfo>);
    }
}

/**
 * TunnelInfo 对应客户端 SQLite tunnels 表。
 */
export class TunnelInfo {
    "id": string;
    "server_id": string;
    "name": string;

    /**
     * tcp | udp | http | https
     */
    "protocol": string;
    "local_ip": string;
    "local_port": number;
    "remote_port"?: number;
    "custom_domain"?: string;
    "subdomain"?: string;
    "enabled": boolean;
    "status": string;

    /** Creates a new TunnelInfo instance. */
    constructor($$source: Partial<TunnelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("server_id" in $$source)) {
            this["server_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("local_ip" in $$source)) {
            this["local_ip"] = "";
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TunnelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInfo($$parsedSource as Partial<TunnelInfo>);
    }
}
