// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agent} from '../models';
import {db} from '../models';
import {frpc} from '../models';
import {sql} from '../models';

export function AddServer(arg1:main.AddServerInput):Promise<string>;

export function AddTunnel(arg1:main.AddTunnelInput):Promise<string>;

export function CheckServerCapabilities(arg1:string):Promise<agent.Capabilities>;

export function Close():Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function EmitLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GenerateFrpcConfig(arg1:string):Promise<string>;

export function Init(arg1:db.Repo,arg2:frpc.Manager):Promise<void>;

export function InitForTest(arg1:string):Promise<void>;

export function IsFrpcRunning(arg1:string):Promise<boolean>;

export function ListServers():Promise<Array<main.ServerInfo>>;

export function ListTunnels(arg1:string):Promise<Array<main.TunnelInfo>>;

export function RestartFrpc(arg1:string):Promise<void>;

export function SetDatabase(arg1:sql.DB):Promise<void>;

export function StartFrpc(arg1:string):Promise<void>;

export function StopFrpc(arg1:string):Promise<void>;

export function UpdateServerByID(arg1:string,arg2:main.AddServerInput):Promise<void>;

export function UpdateTunnelByID(arg1:string,arg2:main.AddTunnelInput):Promise<void>;
