// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateFrpcConfig(arg1) {
  return window['go']['main']['App']['GenerateFrpcConfig'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListTunnels(arg1) {
  return window['go']['main']['App']['ListTunnels'](arg1);
}

export function RestartFrpc(arg1) {
  return window['go']['main']['App']['RestartFrpc'](arg1);
}

export function StartFrpc(arg1) {
  return window['go']['main']['App']['StartFrpc'](arg1);
}

export function StopFrpc(arg1) {
  return window['go']['main']['App']['StopFrpc'](arg1);
}
