// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function AddTunnel(arg1) {
  return window['go']['main']['App']['AddTunnel'](arg1);
}

export function CheckServerCapabilities(arg1) {
  return window['go']['main']['App']['CheckServerCapabilities'](arg1);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function EmitLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['EmitLog'](arg1, arg2, arg3);
}

export function GenerateFrpcConfig(arg1) {
  return window['go']['main']['App']['GenerateFrpcConfig'](arg1);
}

export function Init(arg1, arg2) {
  return window['go']['main']['App']['Init'](arg1, arg2);
}

export function InitForTest(arg1) {
  return window['go']['main']['App']['InitForTest'](arg1);
}

export function IsFrpcRunning(arg1) {
  return window['go']['main']['App']['IsFrpcRunning'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListTunnels(arg1) {
  return window['go']['main']['App']['ListTunnels'](arg1);
}

export function RestartFrpc(arg1) {
  return window['go']['main']['App']['RestartFrpc'](arg1);
}

export function SetDatabase(arg1) {
  return window['go']['main']['App']['SetDatabase'](arg1);
}

export function StartFrpc(arg1) {
  return window['go']['main']['App']['StartFrpc'](arg1);
}

export function StopFrpc(arg1) {
  return window['go']['main']['App']['StopFrpc'](arg1);
}

export function UpdateServerByID(arg1, arg2) {
  return window['go']['main']['App']['UpdateServerByID'](arg1, arg2);
}

export function UpdateTunnelByID(arg1, arg2) {
  return window['go']['main']['App']['UpdateTunnelByID'](arg1, arg2);
}
