// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateFrpcConfig(arg1:string):Promise<string>;

export function ListServers():Promise<Array<main.ServerInfo>>;

export function ListTunnels(arg1:string):Promise<Array<main.TunnelInfo>>;

export function RestartFrpc(arg1:string):Promise<void>;

export function StartFrpc(arg1:string):Promise<void>;

export function StopFrpc(arg1:string):Promise<void>;
