// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AllowPortRange 是 capabilities 响应里的端口范围项。
 */
export class AllowPortRange {
    "start": number;
    "end": number;

    /** Creates a new AllowPortRange instance. */
    constructor($$source: Partial<AllowPortRange> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AllowPortRange instance from a string or object.
     */
    static createFrom($$source: any = {}): AllowPortRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AllowPortRange($$parsedSource as Partial<AllowPortRange>);
    }
}

/**
 * Capabilities 对应 GET /api/capabilities 响应。
 */
export class Capabilities {
    "frps_running": boolean;
    "frps_version": string;
    "bind_port": number;
    "allow_ports": AllowPortRange[];
    "support_tcp": boolean;
    "support_udp": boolean;
    "support_http": boolean;
    "support_https": boolean;
    "vhost_http_port": number;
    "vhost_https_port": number;
    "subdomain_host": string;
    "allowed_root_domains": string[];

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("frps_running" in $$source)) {
            this["frps_running"] = false;
        }
        if (!("frps_version" in $$source)) {
            this["frps_version"] = "";
        }
        if (!("bind_port" in $$source)) {
            this["bind_port"] = 0;
        }
        if (!("allow_ports" in $$source)) {
            this["allow_ports"] = [];
        }
        if (!("support_tcp" in $$source)) {
            this["support_tcp"] = false;
        }
        if (!("support_udp" in $$source)) {
            this["support_udp"] = false;
        }
        if (!("support_http" in $$source)) {
            this["support_http"] = false;
        }
        if (!("support_https" in $$source)) {
            this["support_https"] = false;
        }
        if (!("vhost_http_port" in $$source)) {
            this["vhost_http_port"] = 0;
        }
        if (!("vhost_https_port" in $$source)) {
            this["vhost_https_port"] = 0;
        }
        if (!("subdomain_host" in $$source)) {
            this["subdomain_host"] = "";
        }
        if (!("allowed_root_domains" in $$source)) {
            this["allowed_root_domains"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        const $$createField3_0 = $$createType1;
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allow_ports" in $$parsedSource) {
            $$parsedSource["allow_ports"] = $$createField3_0($$parsedSource["allow_ports"]);
        }
        if ("allowed_root_domains" in $$parsedSource) {
            $$parsedSource["allowed_root_domains"] = $$createField11_0($$parsedSource["allowed_root_domains"]);
        }
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

// Private type creation functions
const $$createType0 = AllowPortRange.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
