// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AllowPortRange 是 capabilities 响应里的端口范围项。
 */
export interface AllowPortRange {
    "start": number;
    "end": number;
}

/**
 * Capabilities 对应 GET /api/capabilities 响应。
 */
export interface Capabilities {
    "frps_running": boolean;
    "frps_version": string;
    "bind_port": number;
    "allow_ports": AllowPortRange[] | null;
    "support_tcp": boolean;
    "support_udp": boolean;
    "support_http": boolean;
    "support_https": boolean;
    "vhost_http_port": number;
    "vhost_https_port": number;
    "subdomain_host": string;
    "allowed_root_domains": string[] | null;
}
