// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings 是客户端应用设置。
 * 零值约定：LogRetentionDays=0 表示不落盘日志（与 v0.1 内存日志行为一致）。
 */
export interface Settings {
    /**
     * 关闭窗口时最小化到托盘
     */
    "close_to_tray": boolean;

    /**
     * 开机自启
     */
    "auto_start": boolean;

    /**
     * 日志保留天数，0=不落盘
     */
    "log_retention_days": number;

    /**
     * 配置目录（只读展示，当前不支持修改）
     */
    "config_dir": string;

    /**
     * 窗口状态持久化（DIP 坐标，与 Wails Position()/Size() 返回值一致）。
     * 由窗口移动/缩放/最大化事件自动写回，前端设置页不感知这些字段。
     * WindowWidth/WindowHeight 为 0 时表示无记录，使用默认尺寸。
     */
    "window_maximised": boolean;
    "window_x": number;
    "window_y": number;
    "window_width": number;
    "window_height": number;
}
